### PR TITLE
Update mechatronics.yml

### PR DESCRIPTION
**Pull request by MrAndrea**
To add Gianluca Milani and Enrico Valli to mechatronics repository

### CODE REVIEW

**Review by pattacini — APPROVED** [review]
Oki @MrAndrea 👍🏻 

Quick comment: next time, please make a fork instead of going with a branch.

**Comment by MrAndrea** [comment]
Ok thanks @pattacini for the hint.

**Comment by pattacini** [comment]
cc @marcellosavoldi for reference.

**Comment by MrAndrea** [comment]
@pattacini I made changes using the browser, and I had only 2 choices:

image

Did your [hint](https://github.com/icub-tech-iit/outside-collaborators/pull/28#pullrequestreview-539223350) refer to another way?

**Comment by pattacini** [comment]
>Did your hint refer to another way?

Yes! You ought to fork the repo first.
Here's some doc on [forks and pull-requests](https://guides.github.com/activities/forking).

**Pull request merged**
