### PR TITLE
Add one user to the mechanical repositories

### PR DESCRIPTION
**Pull request by fiorisi**
As per title this PR adds one user to the mechanical repositories.

### CODE REVIEW

**Review by pattacini — COMMENTED** [review]
@fiorisi any particular reason why @divyashah is not a member of the group `mws-iit/mech` instead?

**Comment by fiorisi** [comment]
No, actually it is a better fit. I update the PR. 
Thanks @pattacini!

**Review by pattacini — CHANGES_REQUESTED** [review]
@fiorisi you should rather modify the file describing the `mws-iit.mech` group in the `repos` directory.

**Comment by fiorisi** [comment]
@pattacini, @divyashah  was actually already part of the group `mws-iit/mech`.
So we have to add him only to the `mechatronics` repository. In this case we don't want to add the whole `mws-iit/mech' group.

**Review by pattacini — APPROVED** [review]

**Comment by pattacini** [comment]
Ok then!

**Pull request merged**
